language: go
go:
- 1.8
sudo: false

install: make setup

script: make check test

before_deploy:
- mkdir -p bin
- GOOS=linux GOARCH=amd64  go build -o bin/parsopt-Linux-x86_64  -ldflags="-X main.version=$TRAVIS_TAG"
- GOOS=darwin GOARCH=amd64 go build -o bin/parsopt-Darwin-x86_64 -ldflags="-X main.version=$TRAVIS_TAG"

deploy:
  provider: releases
  api_key:
    secure: xxx
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    tags: true
    go: 1.8
